const spots=[[[0.18, 0.12], [0.06, 0.23], [0.44, 0.1], [0.65, 0.1], [0.89, 0.1]], [[0.13, 0.22], [0.14, 0.41], [0.38, 0.43], [0.56, 0.42], [0.66, 0.38]], [[0.08, 0.19], [0.1, 0.35], [0.48, 0.13], [0.39, 0.35], [0.48, 0.42]], [[0.48, 0.1], [0.86, 0.1], [0.11, 0.31], [0.29, 0.39], [0.47, 0.43]], [[0.13, 0.13], [0.17, 0.28], [0.35, 0.37], [0.52, 0.1], [0.61, 0.26]]];
export const games={escape:'Escape the Nexus',odin:'ODIN',tapple:'Nexus Word Rush (Tapple)',shadow:'Shadow Signal',memory:'Memory Flip',trivia:'Trivia Clash',pattern:'Pattern Pulse',scramble:'Word Scramble',spot:'Spot the Difference'};
const pick=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
import {questions5,questions6,words} from './question-bank.mjs';
export {questions5,questions6,words};
const categories={Animals:['ant','bear','cat','dog','elephant','fox','giraffe','horse','iguana','jaguar','kangaroo','lion','monkey','newt','owl','penguin','quail','rabbit','snake','tiger','urchin','vulture','wolf','yak','zebra','cheetah','duck','bee','chicken','goat','sheep','cow','pig','deer','moose','otter','beaver','raccoon','squirrel','mouse','rat','bat','whale','seal','walrus','shark','trout','salmon','eagle','hawk','crow','robin','swan','goose','turkey','crab','lobster','shrimp','octopus','squid','turtle','frog','toad'],Foods:['apple','banana','carrot','donut','egg','fish','grape','honey','icecream','jam','kiwi','lemon','mango','noodles','orange','pizza','quinoa','rice','soup','toast','waffle','yogurt','zucchini']};
function next(s){s.turn=(s.turn+(s.direction||1)+s.players.length)%s.players.length;s.deadline=Date.now()+(s.game==='tapple'?10000:20000)}
function finish(s){s.phase='finished';const top=Math.max(...s.players.map(p=>p.score));s.winners=s.players.filter(p=>p.score===top).map(p=>p.id)}
function round(s){s.round++;if(s.round>=10){finish(s);return}s.answered=[];if(s.game==='trivia')s.question=(s.grade===6?questions6:questions5)[s.order[s.round]];if(s.game==='scramble'){s.answer=words[s.order[s.round]];s.prompt=shuffle([...s.answer]).join(' ')}if(s.game==='pattern'){s.pulse=Array.from({length:s.round+2},()=>Math.floor(Math.random()*4));s.answer=s.pulse.join(',');s.prompt='Watch the lights, then repeat the sequence';s.options=[]}s.deadline=Date.now()+30000}
export function start(s){if(s.players.length<(s.game==='shadow'?3:2))throw Error(s.game==='shadow'?'Shadow Signal needs at least three heroes':'Invite at least one friend');s.phase='playing';s.players.forEach(p=>p.score=0);s.turn=0;s.round=-1;s.deadline=Date.now()+20000;if(s.game==='escape'){s.seals={};s.challenges={};s.escapeAnswers={};for(const [playerIndex,p] of s.players.entries()){if(s.rescueQuestions?.[p.id]){const q=s.rescueQuestions[p.id];s.challenges[p.id]={prompt:q[0],options:q[1]};s.escapeAnswers[p.id]=String(q[1][q[2]]);s.seals[p.id]=false;continue;}const n=3+Math.floor(Math.random()*6),m=2+Math.floor(Math.random()*6);const answer=p.grade===6?n*(m+2):n*m;s.challenges[p.id]={prompt:p.grade===6?`A seal needs ${n} × (${m} + 2) sparks. How many?`:`Find ${n} groups of ${m} crystals. How many total?`,options:shuffle([answer,answer+3,answer-2])};s.escapeAnswers[p.id]=String(answer);s.seals[p.id]=false;}s.deadline=Date.now()+300000;}else if(s.game==='odin'){s.direction=1;s.discard=[];s.deck=shuffle(['violet','blue','green','gold'].flatMap(color=>[...Array.from({length:10},(_,value)=>({color,value})),...['skip','reverse','+2'].map(value=>({color,value}))].flatMap(c=>[c,{...c}])).concat(Array.from({length:4},()=>({color:'wild',value:'wild'}))));s.hands=Object.fromEntries(s.players.map(p=>[p.id,s.deck.splice(0,7)]));s.top=s.deck.pop();while(s.top.value==='wild'){s.deck.unshift(s.top);s.top=s.deck.pop()}s.drawn=false;s.moves=0}else if(s.game==='memory'){s.board=shuffle(Array.from({length:8},(_,i)=>[i,i]).flat());s.matched=[];s.revealed=[];s.hideAt=0}else if(s.game==='shadow'){s.spy=pick(s.players).id;s.word=pick(['Library','Cafeteria','Playground','Gym','Museum']);s.votes={};s.deadline=Date.now()+120000}else if(s.game==='tapple'){s.deadline=Date.now()+10000;s.category=pick(Object.keys(categories));s.used=[];s.eliminated=[]}else if(s.game==='spot'){s.found=[];s.set=Math.floor(Math.random()*5)}else{s.order=s.order||shuffle(Array.from({length:s.game==='trivia'?(s.grade===6?questions6:questions5).length:words.length},(_,i)=>i)).slice(0,10);round(s)}return s}
export function tick(s){if(s.phase!=='playing')return s;if(s.game==='memory'&&s.hideAt&&Date.now()>=s.hideAt){s.revealed=[];s.hideAt=0;next(s)}if(Date.now()>s.deadline){if(s.game==='escape')finish(s);else if(['trivia','pattern','scramble'].includes(s.game))round(s);else if(s.game==='shadow'){s.players.forEach(p=>p.score=p.id===s.spy?1:0);finish(s)}else if(s.game==='tapple'){const p=s.players[s.turn];s.eliminated.push(p.id);const left=s.players.filter(p=>!s.eliminated.includes(p.id));if(left.length===1){finish(s);s.winners=[left[0].id]}else{do{next(s)}while(s.eliminated.includes(s.players[s.turn].id))}}else if(s.game==='spot')finish(s);else{if(s.game==='memory'){s.revealed=[];s.hideAt=0;}if(s.game==='odin')s.drawn=false;next(s)}}return s}
export function move(s,pid,a){tick(s);if(s.phase!=='playing')throw Error('This round has ended');const p=s.players.find(p=>p.id===pid);if(!p)throw Error('Join the room first');const turn=s.players[s.turn].id===pid;if(['odin','tapple','memory'].includes(s.game)&&!turn)throw Error('Wait for your turn');
if(s.game==='escape'){if(s.seals[pid])throw Error('Your seal is already open');if(String(a.answer)!==s.escapeAnswers[pid])throw Error('Try another answer—the squad needs your seal');s.seals[pid]=true;p.score=1;if(Object.values(s.seals).every(Boolean)){finish(s);s.winners=s.players.map(p=>p.id)}}else if(s.game==='odin'){const h=s.hands[pid];if(!s.deck.length&&s.discard.length){s.deck=shuffle(s.discard.map(c=>c.value==='wild'?{color:'wild',value:'wild'}:c));s.discard=[];}if(a.type==='draw'){if(s.drawn)throw Error('You already drew');if(!s.deck.length)throw Error('No cards left — pass');h.push(s.deck.pop());s.drawn=true}else if(a.type==='pass'){if(!s.drawn&&s.deck.length)throw Error('Draw before passing');next(s);s.drawn=false}else{const i=Number(a.index),c=h[i];if(!Number.isInteger(i)||!c||!(c.color==='wild'||c.color===s.top.color||c.value===s.top.value))throw Error('Match the color or number');if(c.color==='wild'&&!['violet','blue','green','gold'].includes(a.color))throw Error('Choose a wild color');s.discard.push(s.top);s.top=h.splice(i,1)[0];if(s.top.color==='wild')s.top.color=a.color;s.moves++;if(!h.length){p.score=1;finish(s)}else{if(s.top.value==='reverse')s.direction=-s.direction;next(s);if(s.top.value==='skip'||(s.top.value==='reverse'&&s.players.length===2))next(s);if(s.top.value==='+2'){const target=s.players[s.turn].id;for(let j=0;j<2;j++){if(!s.deck.length&&s.discard.length){s.deck=shuffle(s.discard.map(c=>c.value==='wild'?{color:'wild',value:'wild'}:c));s.discard=[];}if(s.deck.length)s.hands[target].push(s.deck.pop())}next(s)}s.drawn=false}}if(s.moves>400)finish(s)}
else if(s.game==='memory'){if(s.hideAt)throw Error('Wait for the cards to turn over');const i=Number(a.index);if(!Number.isInteger(i)||i<0||i>=16||s.matched.includes(i)||s.revealed.includes(i))throw Error('Choose a hidden card');s.revealed.push(i);if(s.revealed.length===2){const [x,y]=s.revealed;if(s.board[x]===s.board[y]){s.matched.push(x,y);s.revealed=[];p.score++;if(s.matched.length===16)finish(s)}else{s.hideAt=Date.now()+1300;s.deadline=Date.now()+21000}}}
else if(s.game==='tapple'){const word=String(a.word||'').toLowerCase().replace(/[^a-z]/g,'');if(!categories[s.category].includes(word)&&!categories[s.category].includes(word.replace(/s$/,'')))throw Error('Hmm, try another '+(s.category==='Animals'?'animal':'food')+'!');const letter=word[0];if(s.used.includes(letter))throw Error('That letter was used');s.used.push(letter);p.score++;if(s.used.length>=20)s.used=[];do{next(s)}while(s.eliminated.includes(s.players[s.turn].id))}
else if(s.game==='shadow'){if(s.votes[pid])throw Error('You already voted');if(!s.players.some(x=>x.id===a.vote)||a.vote===pid)throw Error('Choose another hero');s.votes[pid]=a.vote;if(Object.keys(s.votes).length===s.players.length){const counts={};Object.values(s.votes).forEach(id=>counts[id]=(counts[id]||0)+1);const top=Math.max(...Object.values(counts));const caught=counts[s.spy]===top&&Object.values(counts).filter(n=>n===top).length===1;s.players.forEach(x=>x.score=(caught?x.id!==s.spy:x.id===s.spy)?1:0);finish(s)}}
else if(s.game==='spot'){const x=Number(a.x),y=Number(a.y),i=spots[s.set].findIndex(([sx,sy])=>Math.abs(x-sx)<.055&&(Math.abs(y-sy)<.04||Math.abs(y-sy-.5)<.04));if(!Number.isFinite(x)||!Number.isFinite(y)||i<0)throw Error('That tap did not match a difference. Compare both pictures.');if(s.found.includes(i))throw Error('That difference was already found');s.found.push(i);p.score++;s.deadline=Date.now()+60000;if(s.found.length===5)finish(s)}
else{if(a.round!==s.round)throw Error('A new question has started');if(s.answered.includes(pid))throw Error('You already answered');s.answered.push(pid);const ok=s.game==='trivia'?Number(a.answer)===s.question[2]:String(a.answer).trim().toUpperCase()===String(s.answer);s.feedback=s.feedback||{};s.feedback[pid]={correct:ok,answer:s.game==='trivia'?s.question[1][s.question[2]]:s.answer,why:s.game==='trivia'?s.question[3]:'Compare your answer with the puzzle.'};if(ok)p.score++;if(s.answered.length===s.players.length)round(s)}return s}
export function view(s,pid){const v=structuredClone(s);if(v.feedback)v.feedback=v.feedback[pid];if(v.game==='escape'){v.challenge=v.challenges[pid];delete v.challenges;delete v.escapeAnswers;delete v.rescueQuestions;}delete v.deck;delete v.discard;delete v.order;delete v.answer;delete v.base;delete v.step;if(v.question)v.question=v.question.slice(0,2);if(v.hands){v.hand=v.hands[pid]||[];v.handCounts=Object.fromEntries(Object.entries(v.hands).map(([k,h])=>[k,h.length]));delete v.hands}if(v.board)v.board=v.board.map((c,i)=>v.matched.includes(i)||v.revealed.includes(i)?c:null);if(v.spy){v.role=pid===v.spy?'Shadow':'Hero';v.secret=pid===v.spy?'Find the location without being spotted.':v.word;if(v.phase!=='finished'){delete v.spy;delete v.word;v.votes=Object.keys(v.votes)}}return v}
