import {createClient} from '@supabase/supabase-js';
export const supabase=createClient('https://reccddfusealreknvjfj.supabase.co','REPLACE_WITH_YOUR_API_KEY',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'hahn-academy-auth'}});
export async function api(op:string,data:Record<string,unknown>={}){const {data:{session}}=await supabase.auth.getSession();const child=localStorage.getItem('hahnChildSession');if(!session&&!child&&!['child-create','child-login'].includes(op))throw Error('Choose your character and enter your six-digit code');const r=await fetch('https://reccddfusealreknvjfj.supabase.co/functions/v1/academy',{method:'POST',headers:{'Content-Type':'application/json',apikey:'REPLACE_WITH_YOUR_API_KEY',...(session?{Authorization:'Bearer '+session.access_token}:child?{Authorization:'Bearer child.'+child}:{})},body:JSON.stringify({op,...data})});const out=await r.json();if(!r.ok||out.error)throw Error(out.error||'Connection interrupted');return out;}
export async function squad(op:string,data:Record<string,unknown>={}){let secret=localStorage.getItem('nexusOnlineSecret');const call=async(op:string,data:Record<string,unknown>={})=>{const r=await fetch('https://reccddfusealreknvjfj.supabase.co/functions/v1/nexus',{method:'POST',headers:{'Content-Type':'application/json',apikey:'REPLACE_WITH_YOUR_API_KEY'},body:JSON.stringify({op,secret,...data})});const out=await r.json();if(!r.ok||out.error)throw Error(out.error||'Connection interrupted');return out};if(!secret){const r=await call('register');secret=r.secret;localStorage.setItem('nexusOnlineSecret',secret!)}const {data:{session}}=await supabase.auth.getSession();if(session||localStorage.getItem('hahnChildSession')){const identity=await api('nexus-identity',{secret});secret=identity.secret;localStorage.setItem('nexusOnlineSecret',secret!)}return call(op,data);}
export const asset=(path:string)=>'/_nexus-test/'+path;
export type Profile={id:string;alias:string;role:string;hero:string|null;requested_grade:number|null;verified_grade:number|null;nexling:string|null;growth:number;coins:number;skill_points:number;skills:Record<string,number>;owned:string[];equipped:Record<string,string>;dorm:{item:string;x:number;y:number}[];mentor:string;chronicle:number;streak:number;surge_uses:number;link_code:string;guardian_code:string};
export type Snapshot={rewardStatus?:import('./reward-badge').RewardStatus|null;profile:Profile;membership:any;children:any[];classes:any[];missions:any[];submissions:any[];events:any[];rsvps:string[];ledger:any[];pending:any[];parentRequests:any[]};

export async function signOut(){try{if(localStorage.getItem('hahnChildSession'))await api('child-logout')}finally{localStorage.removeItem('hahnChildSession');localStorage.removeItem('nexusOnlineSecret');localStorage.removeItem('nexusRoom');for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith('hahn-rebuild-room'))localStorage.removeItem(key)}await supabase.auth.signOut({scope:'local'});window.dispatchEvent(new Event('hahn:identity'));}}
