import React,{useEffect,useState} from 'react';
// @ts-expect-error Existing validated game engine shared by solo and server rooms.
import {start,move,tick,view,questions5,questions6,words} from '../../server/games.mjs';
import {asset,Profile,api} from './api';
import {Run} from './main';
import {WordBuilder} from './word-builder';
import {Pulse} from './pulse';
import {GameBoard} from './multiplayer';
const choose=(a:any[])=>a[Math.floor(Math.random()*a.length)];
function newGame(game:string,grade:number,order?:number[]){return start({game,grade,order,phase:'lobby',host:'solo',players:[{id:'solo',nickname:'You',score:0},{id:'bot',nickname:'Nexus Guide',score:0},...(game==='shadow'?[{id:'bot2',nickname:'Archive Guardian',score:0}]:[])],turn:0})}
export function Solo(props:{game:string;profile:Profile|null;run:Run}){return props.game==='pattern'?<Pulse/>:props.game==='builder'?<WordBuilder profile={props.profile}/>:<EngineSolo {...props}/>}
function EngineSolo({game,profile,run}:{game:string;profile:Profile|null;run:Run}){const [state,setState]=useState<any>(()=>newGame(game,profile?.verified_grade||profile?.requested_grade||5)),[error,setError]=useState(''),[loading,setLoading]=useState(['trivia','scramble'].includes(game));
const reset=async()=>{setLoading(true);try{const grade=profile?.verified_grade||profile?.requested_grade||5;let order;if(['trivia','scramble'].includes(game)){const qs=game==='scramble'?words.map((w:string)=>[null,null,null,null,'word:'+w]):grade===6?questions6:questions5;if(profile){const {ids}=await api('reserve-questions',{game});order=ids.map((id:string)=>qs.findIndex((q:any)=>q[4]===id));}else{const key='hahn-seen-questions';const seen=new Set(JSON.parse(localStorage.getItem(key)||'[]'));order=qs.map((_:any,i:number)=>i).filter((i:number)=>!seen.has(qs[i][4])).sort(()=>Math.random()-.5).slice(0,10);if(order.length<10)throw Error('New challenges are on the way. Try a different game.');order.forEach((i:number)=>seen.add(qs[i][4]));localStorage.setItem(key,JSON.stringify([...seen]));}}setState(newGame(game,grade,order));setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
useEffect(()=>{if(['trivia','scramble'].includes(game))reset()},[game,profile?.id]);
const action=(a:any)=>{try{const s=structuredClone(state);move(s,'solo',a);setState(s);setError('')}catch(e){setError((e as Error).message)}};
useEffect(()=>{const timer=setInterval(()=>setState((s:any)=>{const n=structuredClone(s);tick(n);return n}),800);return ()=>clearInterval(timer)},[]);
useEffect(()=>{if(state.phase!=='playing'||state.players[state.turn]?.id==='solo'||!['odin','memory','tapple'].includes(game))return;const timer=setTimeout(()=>{try{const n=structuredClone(state);const id=n.players[n.turn].id;if(game==='memory'){if(n.hideAt)return;const choices=n.board.map((_:any,i:number)=>i).filter((i:number)=>!n.matched.includes(i)&&!n.revealed.includes(i));move(n,id,{index:choose(choices)})}if(game==='odin'){const idx=n.hands[id].findIndex((c:any)=>c.color==='wild'||c.color===n.top.color||c.value===n.top.value);move(n,id,idx>=0?{type:'play',index:idx,color:'blue'}:n.drawn?{type:'pass'}:{type:'draw'})}if(game==='tapple'){const foods=['apple','banana','carrot','donut','egg','fish','grape','honey','icecream','jam','kiwi','lemon','mango','noodles','orange','pizza','quinoa','rice','soup','toast','waffle','yogurt','zucchini'];const animals=['ant','bear','cat','dog','elephant','fox','giraffe','horse','iguana','jaguar','kangaroo','lion','monkey','newt','owl','penguin','quail','rabbit','snake','tiger','urchin','vulture','wolf','yak','zebra'];const words=(n.category==='Foods'?foods:animals).filter(w=>!n.used.includes(w[0]));if(words.length)move(n,id,{word:choose(words)})}setState(n)}catch{}},700);return ()=>clearTimeout(timer)},[state,game]);
useEffect(()=>{if(['trivia','pattern','scramble'].includes(game)&&state.phase==='playing'&&!state.answered.includes('bot')){const t=setTimeout(()=>{setState((s:any)=>{const n=structuredClone(s);if(n.phase==='playing'&&!n.answered.includes('bot'))move(n,'bot',{round:n.round,answer:game==='trivia'?choose([0,1,2]):game==='pattern'?choose(n.options):Math.random()<.5?n.answer:'TRY'});return n})},3500);return ()=>clearTimeout(t)}},[state.round,state.phase,game]);
return <><div className="panel game-top"><span className="pill">SOLO PRACTICE · {game==='trivia'?`GRADE ${profile?.verified_grade||profile?.requested_grade||5}`:'NO COINS AT STAKE'}</span><button className="text-button" onClick={reset}>Restart</button></div>{error&&<p className="notice">{error}</p>}{loading?<p>Opening fresh challenges…</p>:error&&['trivia','scramble'].includes(game)?null:<GameBoard room={view(state,'solo')} player="solo" action={action}/>}{game==='shadow'&&<div className="panel"><p>Shadow Signal works best with real friends giving clues aloud. Open Squad Games to play a private live room.</p><button className="secondary" onClick={()=>{const n=structuredClone(state);n.players.filter((p:any)=>p.id!=='solo').forEach((p:any)=>{if(!n.votes[p.id])move(n,p.id,{vote:'solo'})});setState(n)}}>Reveal practice result</button></div>}<p className="muted">Solo practice is available without an account. Verified learning challenges and adult-approved missions earn saved Nexus Coins.</p></>}
