(() => {
  const hairNames=['Long Layered','High Ponytail','Shoulder Waves','Anime Bob','Twin Braids','Messy Bun','Wolf Cut','Colored Tips','Twin Tails','Nexus Energy'];
  const outfitNames=['Nexus Hoodie','Pulse Tracksuit','Academy Uniform','Shadow Streetwear','Varsity Cargos','Academy Remix','Graphic Spark','Training Armor','Prism Streetwear','Nexus Radiance'];
  const extraNames=['None','Starlight Glasses','Star Hair Clips','Violet Bow','Nexus Headphones','Crossbody Satchel','Lunar Bracelets','Crystal Necklace','Comet Scarf','Pulse Wrist Device','Energy Halo'];
  const prices=[0,0,0,100,200,300,400,500,750,1000];
  const categories={hair:{label:'HAIR',symbol:'✦',names:hairNames},outfit:{label:'OUTFITS',symbol:'◈',names:outfitNames},extra:{label:'EXTRAS',symbol:'✧',names:extraNames},face:{label:'FACE',symbol:'◉',names:['Classic','Freckles','Focus marks']},makeup:{label:'DETAILS',symbol:'✳',names:['None','Rosy cheeks','Star shimmer']}};
  const asset={girl:{hair:'character-lab/girl-hair-cutout.webp',outfit:'character-lab/girl-outfits-safe.webp'},boy:{hair:'character-lab/boy-hair-cutout.webp',outfit:'character-lab/boy-outfits-cutout.webp'},extra:'character-lab/accessories-v2.png'};
  const images={};for(const [key,url] of Object.entries({...asset.girl,...{'girlOutfit':asset.girl.outfit,'boyHair':asset.boy.hair,'boyOutfit':asset.boy.outfit,extra:asset.extra}})){const im=new Image();im.src=url;images[key]=im}
  let saved,selected,category='hair',owned={},activeGender='girl';
  const dialog=document.createElement('dialog');dialog.id='heroStudio';
  dialog.innerHTML=`<div class="studio-shell"><header class="studio-header"><div><small>THE HIDDEN NEXUS</small><h2>CHARACTER LAB</h2></div><div class="studio-balance">✦ <b id="studioPoints">0</b></div><button type="button" id="studioExit" aria-label="Close Character Lab">×</button></header><div class="studio-main"><div class="studio-stage"><div class="studio-stage-art"></div><div class="studio-character"><canvas id="studioCanvas" width="384" height="640" role="img" aria-label="Your full-body anime hero preview"></canvas></div><div class="studio-hero-label" id="studioHeroLabel">NEXUS HERO</div><div class="studio-style"><button type="button" data-style="girl">GIRL</button><button type="button" data-style="boy">BOY</button></div></div><div class="studio-controls"><div class="studio-categories" id="studioCategories"></div><div class="studio-options" id="studioOptions"></div></div></div><footer class="studio-footer"><div id="studioStatus" aria-live="polite"></div><button type="button" id="studioSave">EQUIP LOOK</button></footer></div>`;
  document.body.append(dialog);
  const q=s=>dialog.querySelector(s),canvas=q('#studioCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
  const image=(kind)=>images[kind==='extra'?'extra':activeGender==='girl'?(kind==='hair'?'hair':'girlOutfit'):(kind==='hair'?'boyHair':'boyOutfit')];
  for(const im of Object.values(images))im.onload=()=>draw();
  function parse(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
  function indexOf(kind,value){const i=categories[kind].names.indexOf(value);return Math.max(0,i)}
  function key(kind,index){const id={hair:'labHair',outfit:'labOutfit',extra:'labExtra'}[kind];return id+':'+(kind==='hair'?activeGender+':':'')+categories[kind].names[index]}
  function unlockCost(){return ['hair','outfit','extra'].reduce((sum,kind)=>{const i=selected[kind];return sum+(i>=(kind==='extra'?4:3)&&!owned[key(kind,i)]?prices[kind==='extra'?i-1:i]:0)},0)}
  function start(){saved=parse('hahnLabHero',null);owned=parse('hahnLabOwned',{});activeGender=saved?.gender==='boy'?'boy':'girl';selected={hair:indexOf('hair',saved?.hair),outfit:indexOf('outfit',saved?.outfit),extra:indexOf('extra',saved?.extra),face:indexOf('face',saved?.face),makeup:indexOf('makeup',saved?.makeup)};category='hair';q('#studioHeroLabel').textContent=(saved?.name||parse('hahnProfile',{})?.heroName||'NEXUS HERO').toUpperCase();dialog.showModal();update()}
  function draw(){if(!dialog.open)return;const outfit=image('outfit'),hair=image('hair');if(!outfit?.complete||!outfit.naturalWidth||!hair?.complete||!hair.naturalWidth)return;ctx.clearRect(0,0,384,640);
    // Both artwork sheets use the same character pose and a 5 by 2 layout.
    const tile=(im,i)=>[(i%5)*im.width/5,Math.floor(i/5)*im.height/2,im.width/5,im.height/2];
    // Outfit tiles are complete figures. Draw one figure, then replace only its
    // head with the chosen hair tile so limbs and footwear never double up.
    ctx.drawImage(outfit,...tile(outfit,selected.outfit),0,0,384,640);
    // Replace the head within its silhouette. Keeping the outfit shoulders and
    // collar avoids a horizontal cut or a second sweatshirt across the chest.
    // Both atlases share the same head position for each style.
    if(selected.hair!==0){
      const head=new Path2D();
      head.moveTo(91,104);head.bezierCurveTo(72,48,112,-6,192,-8);
      head.bezierCurveTo(272,-6,313,48,293,104);
      head.bezierCurveTo(284,126,254,140,225,139);
      head.quadraticCurveTo(192,151,159,139);head.bezierCurveTo(126,140,99,126,91,104);head.closePath();
      ctx.save();ctx.clip(head);ctx.clearRect(0,0,384,190);
      ctx.drawImage(hair,...tile(hair,selected.hair),0,0,384,640);
      ctx.restore();
    }
    const accessory=image('extra');if(accessory?.complete&&accessory.naturalWidth){const i=selected.extra-1,p=[[138,75,108,60],[118,20,147,74],[145,5,95,60],[126,5,132,85],[210,285,110,120],[94,365,60,46],[157,155,65,60],[108,153,167,90],[94,370,65,70],[123,-28,138,100]][i];if(i>=0)ctx.drawImage(accessory,...tile(accessory,i),...p)}
    if(selected.face===1){ctx.fillStyle='#8b514c';for(const x of [162,170,178,206,214,222]){ctx.beginPath();ctx.arc(x,111+(x%3),2,0,Math.PI*2);ctx.fill()}}if(selected.face===2){ctx.strokeStyle='#4b3558';ctx.lineWidth=3;for(const x of [161,218]){ctx.beginPath();ctx.moveTo(x-8,73);ctx.lineTo(x+7,71);ctx.stroke()}}
    if(selected.makeup===1){ctx.fillStyle='#f794b877';for(const x of [166,218]){ctx.beginPath();ctx.ellipse(x,111,14,5,0,0,Math.PI*2);ctx.fill()}}if(selected.makeup===2){ctx.fillStyle='#ffe09a';ctx.font='20px sans-serif';ctx.fillText('✦',235,112)}
  }
  function renderCategories(){const host=q('#studioCategories');host.replaceChildren();for(const [kind,c] of Object.entries(categories)){const b=document.createElement('button');b.type='button';b.className='studio-category';b.setAttribute('aria-label',c.label);b.setAttribute('aria-pressed',category===kind);b.innerHTML='<span>'+c.symbol+'</span><small>'+c.label+'</small>';b.onclick=()=>{category=kind;update()};host.append(b)}}
  function renderOptions(){const host=q('#studioOptions'),c=categories[category];host.replaceChildren();c.names.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.className='studio-option';b.setAttribute('aria-label',name+(i>=(category==='extra'?4:3)&&!owned[key(category,i)]?' locked, '+prices[category==='extra'?i-1:i]+' points':''));b.setAttribute('aria-pressed',selected[category]===i);const art=document.createElement('span');art.className='studio-option-art '+category;const img=category==='hair'?asset[activeGender].hair:category==='outfit'?asset[activeGender].outfit:asset.extra;if(category==='extra'&&i===0){art.textContent='○'}else if(['hair','outfit','extra'].includes(category)){const n=category==='extra'?i-1:i;art.style.backgroundImage='url("'+img+'")';art.style.backgroundPosition=(n%5)*25+'% '+(n>=5?100:0)+'%'}else art.textContent=category==='face'?['◉','⁙','⌁'][i]:['○','●','✦'][i];const caption=document.createElement('span');caption.className='studio-option-caption';caption.textContent=name;const badge=document.createElement('span');badge.className='studio-option-badge';badge.textContent=i>=(category==='extra'?4:3)?(owned[key(category,i)]?'OWNED':prices[category==='extra'?i-1:i]+' ✦'):'FREE';b.append(art,caption);if(i>=(category==='extra'?4:3)) b.append(badge);b.onclick=()=>{selected[category]=i;update()};host.append(b)})}
  function update(){q('#studioPoints').textContent=Number(points);q('[data-style="girl"]').setAttribute('aria-pressed',activeGender==='girl');q('[data-style="boy"]').setAttribute('aria-pressed',activeGender==='boy');renderCategories();renderOptions();draw();const cost=unlockCost(),balance=Number(points);q('#studioStatus').textContent=cost?'Preview is free · '+cost+' points to unlock':'Ready to equip · preview is free';q('#studioSave').textContent=cost?'UNLOCK & EQUIP · '+cost+' ✦':'EQUIP LOOK';q('#studioSave').disabled=cost>balance}
  function commit(){const cost=unlockCost();if(Number(points)<cost){q('#studioStatus').textContent='Earn '+(cost-Number(points))+' more points to unlock this look';return}for(const kind of ['hair','outfit','extra']){const i=selected[kind];if(i>=(kind==='extra'?4:3))owned[key(kind,i)]=1}const hero={...saved,name:saved?.name||parse('hahnProfile',{})?.heroName||'Nexus Hero',gender:activeGender,hair:hairNames[selected.hair],outfit:outfitNames[selected.outfit],extra:extraNames[selected.extra],face:categories.face.names[selected.face],makeup:categories.makeup.names[selected.makeup]};points=Number(points)-cost;localStorage.setItem('hahnLabOwned',JSON.stringify(owned));localStorage.setItem('hahnLabHero',JSON.stringify(hero));save();render();saved=hero;q('#studioStatus').textContent=cost?'Look unlocked and equipped!':'Look equipped!';update();q('#studioStatus').textContent=cost?'Look unlocked and equipped!':'Look equipped!'}
  const confirm=document.createElement('dialog');confirm.id='studioConfirm';confirm.innerHTML='<div class="studio-confirm"><small>CHARACTER LAB</small><h2>Unlock this look?</h2><p id="studioConfirmText"></p><button type="button" id="studioConfirmYes">HOLD TO UNLOCK</button><button type="button" id="studioConfirmNo">KEEP PREVIEWING</button></div>';document.body.append(confirm);let hold;
  q('#studioSave').onclick=()=>{const cost=unlockCost();if(!cost){commit();return}confirm.querySelector('#studioConfirmText').textContent='This look costs '+cost+' points. You have '+points+'. Hold the button to confirm.';confirm.showModal()};
  const yes=confirm.querySelector('#studioConfirmYes');const cancelHold=()=>{clearTimeout(hold);yes.classList.remove('holding')};yes.addEventListener('pointerdown',()=>{yes.classList.add('holding');hold=setTimeout(()=>{confirm.close();cancelHold();commit()},850)});for(const event of ['pointerup','pointerleave','pointercancel'])yes.addEventListener(event,cancelHold);yes.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();confirm.close();commit()}});confirm.querySelector('#studioConfirmNo').onclick=()=>confirm.close();
  q('#studioExit').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});for(const b of dialog.querySelectorAll('[data-style]'))b.onclick=()=>{activeGender=b.dataset.style;selected.hair=0;update()};
  const launch=document.querySelector('[data-action="lab"]');launch.onclick=start;
  const fromRewards=document.querySelector('#rewardsToLab');fromRewards.onclick=()=>{document.querySelector('#rewardsDialog').close();start()};
})();
