(() => {
  const jokes=[
    ['Why did the math book look upset?','It had too many problems.'],['What do you call a sleeping dinosaur?','A dino-snore.'],['Why did the computer go to the doctor?','It had a virus.'],['What do you call a bear with no teeth?','A gummy bear.'],['Why did the banana visit the doctor?','It was not peeling well.'],['How does the moon cut its hair?','Eclipse it.'],['Why did the scarecrow get promoted?','He was outstanding in his field.'],['What did one wall say to the other?','Meet you at the corner.'],['Why did the bicycle fall over?','It was two tired.'],['What kind of tree fits in your hand?','A palm tree.'],
    ['Why did the cookie go to the doctor?','It felt crumby.'],['What do you call a fake noodle?','An impasta.'],['Why are ghosts bad at lying?','You can see right through them.'],['What did the pencil say to the paper?','You have a point.'],['Why did the clock get in trouble?','It tocked too much.'],['What do you call a fish with a bow tie?','Sofishticated.'],['What is a robot’s favorite snack?','Computer chips.'],['Why did the mushroom get invited?','Because he was a fungi.'],['What does a cloud wear under its raincoat?','Thunderwear.'],['Why did the stadium get hot?','All the fans left.'],
    ['How do you organize a space party?','You planet.'],['What did the ocean say to the beach?','Nothing. It waved.'],['Why can’t you trust an atom?','They make up everything.'],['What did the zero say to the eight?','Nice belt!'],['Why did the student eat their homework?','The teacher said it was a piece of cake.'],['What do you call a magician’s dog?','A labracadabrador.'],['Why did the grape stop in the middle of the road?','It ran out of juice.'],['What do you call a snowman in July?','A puddle with memories.'],['Why was the broom late?','It overswept.'],['What do you call cheese that is not yours?','Nacho cheese.'],
    ['Why did the superhero bring a ladder to school?','To reach higher grades.'],['What do you call a dinosaur who knows lots of words?','A thesaurus.'],['Why did the orange lose the race?','It ran out of peel.'],['What is a cat’s favorite color?','Purr-ple.'],['Why did the music teacher need a ladder?','To reach the high notes.'],['What kind of key opens a banana?','A monkey.'],['Why was the calendar nervous?','Its days were numbered.'],['Why did the egg hide?','It was a little chicken.'],['What did the left eye say to the right eye?','Between us, something smells.'],['Why did the astronaut break up with the moon?','They needed space.']
  ];
  const scenarios=[
    ['Have a dragon the size of a hamster','Have a hamster the size of a dragon','Your tiny dragon guards your pencil.','Your huge hamster insists on riding the school bus.'],
    ['Teleport anywhere but always arrive wearing pajamas','Fly anywhere at walking speed','You reached the mission instantly. Your slippers did too.','You floated past traffic while a pigeon raced you.'],
    ['Speak fluent squirrel','Understand what vending machines are thinking','The squirrels have a lot to say about your lunch.','The machine admits it ate your quarter.'],
    ['Turn every sneeze into confetti','Make dramatic theme music play when you enter a room','The hallway is festive. Someone has to sweep.','Everyone knows you are approaching the cafeteria.'],
    ['Have a backpack that holds an entire library','Have shoes that jump over buildings','You can carry every clue. Finding your pencil takes a while.','The roof is easy. Landing near your locker is harder.'],
    ['Be followed by one extremely polite ghost','Have a robot that tells terrible jokes','The ghost says excuse me every time it passes through a wall.','Your robot gets booed by the toaster.'],
    ['Only be able to whisper to villains','Only be able to shout during stealth missions','The villain leans in, giving you a perfect distraction.','The entire hallway hears your secret entrance.'],
    ['Have a cape that changes color with your mood','Have a hat that predicts tomorrow’s weather','Your cape turns neon pink during a surprise quiz.','Your hat warns of rain. It also comments on your hair.'],
    ['Shrink to the size of a pencil for an hour','Grow to the height of a doorway for an hour','You find the clue under the desk, then need a ride back.','You reach the high shelf. Every door is a challenge.'],
    ['Have a pet cloud that follows you','Have a pet shadow that dances','Your cloud gives one person a very personal rain shower.','Your shadow wins the dance contest before you do.'],
    ['Pause time for 10 seconds once a day','Rewind one awkward sentence per day','You catch the falling tray. Nobody knows how.','You get one perfect comeback, eventually.'],
    ['Wear roller skates that can climb walls','Ride a bicycle that floats above puddles','You reach the roof and discover the skates have no brakes.','Your socks stay dry. The bike is very smug.']
  ];
  let remaining=[],lastJoke=-1,choicesLeft=[],round=0,answered=false;
  const pick=(pool,last)=>{if(!pool.length)pool.push(...Array.from({length:jokes.length},(_,i)=>i).filter(i=>i!==last).sort(()=>Math.random()-.5));return pool.pop()};
  const jokeText=document.querySelector('#jokeText');
  document.querySelector('#openJoke').onclick=()=>{document.querySelector('#funDialog').close();document.querySelector('#jokeDialog').showModal();showJoke()};
  document.querySelector('#anotherJoke').onclick=showJoke;
  function showJoke(){lastJoke=pick(remaining,lastJoke);const [q,a]=jokes[lastJoke];jokeText.textContent=q+'\n\n'+a;jokeText.style.whiteSpace='pre-line';document.querySelector('#anotherJoke').textContent='ANOTHER JOKE';}
  const q=document.querySelector('#thisThatQ'),host=document.querySelector('#thisThatChoices'),next=document.querySelector('#thisThatNext');
  const outcome=document.createElement('p');outcome.id='thisThatOutcome';outcome.style.cssText='min-height:70px;text-align:center;color:#f4df9b;font-size:19px;font-weight:700';host.after(outcome);
  document.querySelector('#thisThatDialog h2').textContent='🤪 WOULD YOU RATHER?';
  document.querySelector('#openThisThat').onclick=()=>{document.querySelector('#funDialog').close();document.querySelector('#thisThatDialog').showModal();round=0;choicesLeft=[];advance()};
  next.onclick=advance;
  function advance(){if(!choicesLeft.length)choicesLeft=Array.from({length:scenarios.length},(_,i)=>i).sort(()=>Math.random()-.5);const item=scenarios[choicesLeft.pop()];round++;answered=false;q.textContent='ROUND '+round+' · PICK YOUR POWER';host.replaceChildren();outcome.textContent='Make your choice to reveal what happens.';item.slice(0,2).forEach((label,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=label;b.onclick=()=>{if(answered)return;answered=true;outcome.textContent='✦ '+item[i+2];host.querySelectorAll('button').forEach(x=>x.disabled=true);b.style.borderColor='#ffdc6e';next.textContent=round%5===0?'NEXT QUEST →':'NEXT CHOICE →'};host.append(b)});next.textContent='SKIP THIS ONE →'}
})();
