(() => {
  'use strict';
  const KEY='nexusCollectionV1';
  const catalog=[
    {id:'lantern',name:'Lantern Fragment',rarity:'Common',art:'memory-art/notebook.jpg',lore:'A spark for those who keep searching.'},
    {id:'compass',name:'Wandering Compass',rarity:'Common',art:'memory-art/compass.jpg',lore:'Its needle points toward unanswered questions.'},
    {id:'scroll',name:'Mission Scroll',rarity:'Uncommon',art:'memory-art/mission-scroll.jpg',lore:'An old promise waits to be kept.'},
    {id:'key',name:'Hidden Gate Key',rarity:'Rare',art:'memory-art/nexus-key.jpg',lore:'Only the curious can find the right door.'},
    {id:'portal',name:'Portal Echo',rarity:'Epic',art:'memory-art/portal.jpg',lore:'A doorway that remembers every visitor.'},
    {id:'wolf',name:'First Keeper’s Sigil',rarity:'Legendary',art:'memory-art/wolf.jpg',lore:'The gate remembers its guardian.'},
    {id:'star',name:'Nexus Star',rarity:'Mythic',art:'memory-art/card-back.jpg',lore:'A secret no Keeper has fully explained.'}
  ];
  const themes=['Courage','Curiosity','Kindness','Focus','Discovery','Teamwork'];
  const keeperLines=['The Nexus remembers your effort.','Keep your eyes open. Not every clue announces itself.','You have come farther than you know.'];
  const weekKey=(date=new Date())=>{const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const y=d.getUTCFullYear(),start=new Date(Date.UTC(y,0,1));return `${y}-W${String(Math.ceil((((d-start)/86400000)+1)/7)).padStart(2,'0')}`};
  const today=()=>new Date().toLocaleDateString('en-CA');
  const initial={cards:[],showcase:[],wins:[],streak:0,lastVisit:'',totalEarned:0,perks:{},weekStats:{},keeperSeen:[],revealQueue:[]};
  let state;try{state={...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{state={...initial}};
  const persist=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const app=document.querySelector('.app');if(!app)return;
  const style=document.createElement('style');style.textContent=`
  #nexusUpdateDialog{width:min(720px,calc(100% - 24px));max-height:92dvh;overflow:auto;border-color:#bd8aff}
  #nexusUpdateDialog .modal{padding:18px}.nx-tabs{display:flex;gap:6px;overflow-x:auto;margin:12px 0}.nx-tabs button{white-space:nowrap;padding:9px 12px;border:1px solid #796ab2;border-radius:12px;background:#17183a;color:#fff}
  .nx-tabs button[aria-selected=true]{background:#663bc0}.nx-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(128px,1fr));gap:9px}.nx-card{position:relative;border:2px solid #aaa9c6;border-radius:13px;overflow:hidden;background:#0c1028;color:white;text-align:left;padding:0;min-height:212px}
  .nx-card[data-rarity=Uncommon]{border-color:#66d9aa}.nx-card[data-rarity=Rare]{border-color:#5ab5ff}.nx-card[data-rarity=Epic]{border-color:#bc75ff}.nx-card[data-rarity=Legendary],.nx-card[data-rarity=Mythic]{border-color:#ffd46d;box-shadow:0 0 12px #e7a64088}
  .nx-card img{width:100%;aspect-ratio:1;object-fit:cover;display:block}.nx-card strong,.nx-card small,.nx-card em{display:block;padding:0 8px}.nx-card strong{font-size:14px;margin-top:7px}.nx-card small{color:#efdc9c;font-size:12px;margin:4px 0}.nx-card em{font-style:normal;font-size:12px;color:#b9c5df;margin-bottom:8px}.nx-card b{position:absolute;top:4px;right:5px;border-radius:9px;padding:2px 6px;background:#16172bdd}
  .nx-panel{padding:12px;border:1px solid #565486;border-radius:12px;margin:10px 0;background:#101737}.nx-panel p{margin:6px 0}.nx-panel button,.nx-action{min-height:44px;margin:6px 6px 4px 0;padding:9px 13px;border-radius:11px;border:1px solid #b48cff;background:#342569;color:#fff;font-weight:700}.nx-panel button:disabled{opacity:.5}.nx-meter{height:10px;border-radius:9px;background:#2b3152;overflow:hidden}.nx-meter i{display:block;height:100%;background:linear-gradient(90deg,#8b5ff2,#ffd56c)}
  #nexusReveal{position:fixed;inset:0;z-index:150;background:#030612ec;display:none;place-items:center;padding:24px;text-align:center}#nexusReveal.open{display:grid}.nx-reveal-card{width:min(290px,80vw);animation:nxRise .75s cubic-bezier(.2,.8,.2,1) both}.nx-reveal-card .nx-card{width:100%;min-height:400px}.nx-reveal-card .nx-card img{aspect-ratio:1.1}.nx-reveal-card .nx-card strong{font-size:21px}.nx-reveal-card .nx-card small,.nx-reveal-card .nx-card em{font-size:15px}.nx-reveal-glow{filter:drop-shadow(0 0 28px #ad65ff);animation:nxGlow 1.4s ease-in-out infinite alternate}
  @keyframes nxRise{from{transform:translateY(80px) rotateY(90deg) scale(.65);opacity:0}to{transform:translateY(0) rotateY(0) scale(1);opacity:1}}@keyframes nxGlow{to{filter:drop-shadow(0 0 38px #ffd465)}}@media(prefers-reduced-motion:reduce){.nx-reveal-card,.nx-reveal-glow{animation:none}}

  #nxKeeperMoment,#nxHowGuide{position:fixed;inset:0;z-index:160;display:flex;flex-direction:column;align-items:center;background:radial-gradient(circle at 50% 16%,#512b87,#0b102b 63%,#050818);color:white;overflow:auto;padding:calc(12px + env(safe-area-inset-top)) 16px calc(18px + env(safe-area-inset-bottom))}
  #nxKeeperMoment[hidden],#nxHowGuide[hidden]{display:none}#nxKeeperMoment .nx-keeper-art{width:min(100%,480px);height:min(50dvh,480px);object-fit:contain;object-position:center;background:#100a2c;border:2px solid #ba80ff;border-radius:20px;box-shadow:0 0 32px #9554e599;flex:none}
  .nx-keeper-copy{width:min(100%,480px);text-align:center}.nx-keeper-copy small,.nx-guide-kicker{display:block;letter-spacing:.18em;color:#eac57e;font-weight:900;font-size:13px;margin-top:14px}.nx-keeper-copy h2{font-size:clamp(29px,7vw,42px);margin:6px 0;color:#fff}.nx-keeper-copy p{font-size:clamp(18px,4.5vw,24px);line-height:1.4;margin:10px 0 18px;color:#e8e4ff}
  .nx-guide-button{width:100%;min-height:52px;border:2px solid #f1d898;border-radius:14px;background:linear-gradient(120deg,#874bd8,#43269b);color:white;font-family:inherit;font-size:16px;font-weight:900;letter-spacing:.02em;margin:6px 0;cursor:pointer}.nx-guide-secondary{background:#151c3f;border-color:#685597;color:#e9ddff}
  .nx-guide-inner{width:min(100%,680px);margin:0 auto}.nx-guide-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.nx-guide-head h2{font-size:clamp(29px,7vw,42px);line-height:1.05;margin:7px 0 16px}.nx-guide-head button{min-height:44px;min-width:44px;border:1px solid #9989cb;border-radius:12px;background:#1b2046;color:#fff;font-size:25px}.nx-guide-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.nx-guide-item{border:1px solid #8b75bd;background:#161d46;border-radius:17px;padding:15px;min-height:118px}.nx-guide-item strong{color:#ffe49c;font-size:16px}.nx-guide-item p{color:#e2dafa;font-size:15px;line-height:1.4;margin:8px 0 0}.nx-guide-keeper{font-size:18px;line-height:1.45;border-left:3px solid #d6a5ff;padding:10px 14px;margin:18px 0;color:white;background:#22204a}.nx-guide-inner .nx-guide-button{max-width:680px}
  @media(max-width:500px){.nx-guide-grid{grid-template-columns:1fr}.nx-guide-item{min-height:0}.nx-guide-inner{margin:0 auto}}
  `;document.head.append(style);
  const launch=document.createElement('button');launch.type='button';launch.className='choice';launch.textContent='✦ NEXUS VAULT · WEEKLY QUESTS';launch.style.cssText='display:block;width:calc(100% - 34px);margin:12px 17px;border-color:#b68aff';document.querySelector('#rewardsToVault')?.addEventListener('click',()=>{document.querySelector('#rewardsDialog').close();launch.click()});
  const dlg=document.createElement('dialog');dlg.id='nexusUpdateDialog';dlg.innerHTML='<div class="modal"><small>YOUR NEXUS</small><h2 id="nxTitle">NEXUS VAULT</h2><div class="nx-tabs" role="tablist"></div><div id="nxBody"></div><button class="close" type="button" style="width:100%;margin-top:12px">Back to HQ</button></div>';document.body.append(dlg);
  const reveal=document.createElement('div');reveal.id='nexusReveal';reveal.setAttribute('role','dialog');reveal.setAttribute('aria-modal','true');document.body.append(reveal);
  const tabs=['Vault','Hero','This week','Sensei'];let active='Vault';
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function cardHTML(c,n=1,selected=false){return `<button type="button" class="nx-card" data-card="${c.id}" data-rarity="${c.rarity}" aria-label="${esc(c.name)}, ${c.rarity}${selected?', in Showcase':''}"><img src="${c.art}" alt=""><b>${n>1?'×'+n:selected?'★':''}</b><strong>${esc(c.name)}</strong><small>${c.rarity}</small><em>${esc(c.lore)}</em></button>`}
  function showReveal(c){reveal.innerHTML=`<div class="nx-reveal-glow"><p>✦ FRAGMENT DISCOVERED ✦</p><div class="nx-reveal-card">${cardHTML(c)}</div><button class="nx-action" id="nxRevealContinue">CONTINUE</button></div>`;reveal.classList.add('open');reveal.querySelector('button.nx-card').disabled=true;reveal.querySelector('#nxRevealContinue').focus()}
  reveal.onclick=e=>{if(e.target.id==='nxRevealContinue'){reveal.classList.remove('open');reveal.replaceChildren();const next=state.revealQueue.shift();persist();if(next)showReveal(catalog.find(c=>c.id===next))}};
  function award(id){const c=catalog.find(x=>x.id===id);if(!c)return;state.cards.push(id);state.revealQueue.push(id);persist();if(!reveal.classList.contains('open')){state.revealQueue.shift();persist();showReveal(c)}if(dlg.open)draw()}
  const keeperArt='keeper/day-3.png',keeperMilestoneArt={3:'keeper/day-3.png',7:'keeper/day-7.png',10:'keeper/day-10.png'};
  const guide=document.createElement('section');guide.id='nxHowGuide';guide.hidden=true;guide.setAttribute('role','dialog');guide.setAttribute('aria-modal','true');guide.setAttribute('aria-label','How the Nexus Works');
  guide.innerHTML=`<div class="nx-guide-inner"><div class="nx-guide-head"><div><small class="nx-guide-kicker">THE SENSEI'S GUIDE</small><h2>HOW THE NEXUS WORKS</h2></div><button type="button" id="nxGuideClose" aria-label="Skip for now">×</button></div><div class="nx-guide-grid">
  <div class="nx-guide-item"><strong>⚡ EARN NEXUS POINTS</strong><p>Play games and complete challenges. Save up points to unlock a look you love.</p></div>
  <div class="nx-guide-item"><strong>✦ COLLECT FRAGMENTS</strong><p>Find cards as you explore. Some are easy to discover; rare ones take more effort. Show off your favorites in your Vault.</p></div>
  <div class="nx-guide-item"><strong>🔄 TRADE WITH FRIENDS</strong><p>Open Squad HQ to trade server-verified online fragments with friends.</p></div>
  <div class="nx-guide-item"><strong>🎮 PLAY MINI-GAMES</strong><p>Try trivia, memory, patterns, word games and Spot the Difference. Your grade helps choose the challenge.</p></div>
  <div class="nx-guide-item"><strong>🏠 TAKE ON MISSIONS</strong><p>Home and class missions give you ways to participate beyond games. Some missions will need a parent or teacher connection.</p></div>
  <div class="nx-guide-item"><strong>🧬 CREATE YOUR HERO</strong><p>Try hairstyles, outfits and accessories for free. Spend your points when you save an unlocked look.</p></div>
  <div class="nx-guide-item"><strong>📖 FOLLOW THE STORY</strong><p>Read new episodes as they arrive. Your story access does not depend on spending points.</p></div>
  <div class="nx-guide-item"><strong>👥 FIND YOUR SQUAD</strong><p>Create a private game room in Squad HQ and invite friends using its code.</p></div></div>
  <p class="nx-guide-keeper">“You don’t need to understand everything yet. Explore. Participate. The Nexus will reveal the rest.” — The Sensei</p>
  <button type="button" class="nx-guide-button" id="nxGuideEnter">ENTER THE NEXUS →</button><button type="button" class="nx-guide-button nx-guide-secondary" id="nxGuideSkip">Skip for Now</button></div>`;
  document.body.append(guide);let guideReturn=null;
  function firstFragment(){if(localStorage.getItem('nexusFirstFragmentPending')!=='1')return;localStorage.removeItem('nexusFirstFragmentPending');award('lantern')}
  function closeGuide(){guide.hidden=true;guideReturn?.focus();guideReturn=null;firstFragment()}
  function openGuide(from){guideReturn=from||document.activeElement;document.querySelector('#nxKeeperMoment')?.remove();guide.hidden=false;guide.querySelector('#nxGuideClose').focus({preventScroll:true});guide.scrollTop=0;requestAnimationFrame(()=>{guide.scrollTop=0})}
  for(const id of ['nxGuideClose','nxGuideSkip','nxGuideEnter'])guide.querySelector('#'+id).onclick=closeGuide;
  guide.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closeGuide()}});
  document.querySelector('#openNexusGuide').onclick=()=>{document.querySelector('#settingsDialog').close();openGuide(document.querySelector('#settings'))};
  function keeper(msg,welcome=false,day=0){document.querySelector('#nxKeeperMoment')?.remove();const box=document.createElement('section');box.id='nxKeeperMoment';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label','The Sensei');box.innerHTML=`<img class="nx-keeper-art" src="${keeperMilestoneArt[day]||keeperArt}" alt="The Sensei at the Nexus"><div class="nx-keeper-copy"><small>YOUR GUIDE TO THE NEXUS</small><h2>THE SENSEI</h2><p></p>${welcome?'<button type="button" class="nx-guide-button" data-guide>HOW THE NEXUS WORKS →</button><button type="button" class="nx-guide-button nx-guide-secondary" data-close>Skip for Now</button>':'<button type="button" class="nx-guide-button" data-close>CONTINUE →</button>'}</div>`;box.querySelector('p').textContent=msg;document.body.append(box);box.querySelector('[data-close]').onclick=()=>{box.remove();if(welcome)firstFragment()};box.querySelector('[data-guide]')?.addEventListener('click',()=>openGuide(box.querySelector('[data-guide]')));box.querySelector('button').focus()}
  function visit(){const d=today();if(state.lastVisit===d)return;const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);state.streak=state.lastVisit===yesterday.toLocaleDateString('en-CA')?state.streak+1:1;state.lastVisit=d;persist();if([3,7,10].includes(state.streak)&&!state.keeperSeen.includes('s'+state.streak)){const day=state.streak;state.keeperSeen.push('s'+day);persist();if(day===3){window.nexusPoints=Number(window.nexusPoints)+100;state.totalEarned+=100;persist();window.save();window.render()}else award(day===7?'wolf':'star');const line={3:'The Nexus has taken notice. Three days of effort. 100 Nexus Points are yours.',7:'Your bond strengthens. The First Keeper’s Sigil and its hero rewards are yours.',10:'You have shown discipline worthy of a hero. A rare Nexus Star is yours.'}[day];setTimeout(()=>keeper(`${day}-DAY STREAK · ${line}`,false,day),700)}}
  function draw(){const body=dlg.querySelector('#nxBody');dlg.querySelector('#nxTitle').textContent=active==='Vault'?'NEXUS VAULT':active==='Hero'?'HERO GROWTH':active==='This week'?'THIS WEEK':'THE SENSEI';dlg.querySelector('.nx-tabs').innerHTML=tabs.map(t=>`<button type="button" data-tab="${t}" role="tab" aria-selected="${active===t}">${t}</button>`).join('');const counts=Object.fromEntries(catalog.map(c=>[c.id,state.cards.filter(id=>id===c.id).length]));
    if(active==='Vault'){body.innerHTML=`<p>Discover fragments as you play. Tap a card to add or remove it from your six-card Showcase.</p><div class="nx-panel"><strong>SHOWCASE · ${state.showcase.length}/6</strong><p>${state.showcase.length?state.showcase.map(id=>esc(catalog.find(c=>c.id===id)?.name||'')).join(' · '):'Choose cards below to display here.'}</p></div><div class="nx-grid">${catalog.filter(c=>counts[c.id]).map(c=>cardHTML(c,counts[c.id],state.showcase.includes(c.id))).join('')||'<p>Your first fragment is waiting. Complete a game or weekly quest.</p>'}</div><div class="nx-panel">🔒 Undiscovered fragments: ${catalog.length-Object.keys(counts).filter(k=>counts[k]).length}. Their clues stay hidden until found.</div><button class="nx-action" data-online-trade>OPEN ONLINE CARD TRADING</button><p>Online fragments are earned in squad rooms. This Vault keeps your device collection.</p>`}
    else if(active==='Hero'){const earned=Number(state.totalEarned||0),level=Math.floor(earned/100)+1;body.innerHTML=`<div class="nx-panel"><strong>HERO LEVEL ${level}</strong><p>${earned%100}/100 XP to next level · XP does not decrease when points are spent.</p><div class="nx-meter"><i style="width:${earned%100}%"></i></div></div><div class="nx-panel"><strong>POINTS · ${Number(window.nexusPoints||0)}</strong><p>Choose a small perk. Character Lab has your outfits and accessories.</p><button data-perk="hint">${state.perks.hint||0} hints · Buy 1 for 40 points</button><button data-perk="retry">${state.perks.retry||0} second chances · Buy 1 for 60 points</button></div><div class="nx-panel">NEXT TARGET · ${100-earned%100} XP until Level ${level+1}<p>Earn XP from first game clears, fragment discoveries, and weekly challenges.</p></div>`}
    else if(active==='This week'){const w=weekKey(),stats=state.weekStats[w]||{},idx=Number(w.slice(-2))%themes.length,theme=themes[idx],done=!!stats.anomaly;body.innerHTML=`<div class="nx-panel"><strong>THEME OF THE WEEK · ${theme.toUpperCase()}</strong><p>A fresh focus every week.</p></div><div class="nx-panel"><strong>NEXUS ANOMALY · ${done?'SOLVED':'OPEN'}</strong><p>Solve five signals, then discover a fragment. One reward per week.</p><button data-action="anomaly" ${done?'disabled':''}>${done?'Completed':'BEGIN ANOMALY'}</button></div><div class="nx-panel"><strong>WEEKLY BONUS</strong><p>Complete three different arcade games this week. ${Math.min(stats.games?.length||0,3)}/3</p><button data-action="bonus" ${stats.bonus||((stats.games?.length||0)<3)?'disabled':''}>${stats.bonus?'Claimed':'CLAIM +40 POINTS'}</button></div><div class="nx-panel"><strong>SQUAD CHALLENGE</strong><p>Score three game clears this week to prepare for squad play. ${Math.min(stats.games?.length||0,3)}/3</p><p>Shared squad scores unlock with connected squad accounts.</p></div><div class="nx-panel"><strong>WEEKLY RECAP</strong><p>${stats.games?.length||0} game clears · ${stats.anomaly?'Anomaly solved':'Anomaly waiting'} · ${state.streak} day login streak</p><p>${keeperLines[idx%keeperLines.length]}</p><small>Next week brings a new theme and anomaly.</small></div>`}
    else{body.innerHTML=`<div class="nx-panel"><strong>THE SENSEI GUIDES YOUR JOURNEY</strong><p>${keeperLines[(state.streak||0)%keeperLines.length]}</p><p>Login streak: ${state.streak} day${state.streak===1?'':'s'}. Milestones at 3, 7, and 10 days.</p></div><div class="nx-panel"><strong>SENSEI SECRETS</strong><p>Find fragments and solve the weekly anomaly to reveal pieces of the story. Some discoveries are intentionally hidden.</p></div>`}
  }
  launch.onclick=()=>{active='Vault';draw();dlg.showModal()};dlg.querySelector('.close').onclick=()=>dlg.close();dlg.onclick=e=>{if(e.target.closest('[data-online-trade]')){dlg.close();window.nexusOpenOnline?.();return}const tab=e.target.closest('[data-tab]');if(tab){active=tab.dataset.tab;draw();return}const card=e.target.closest('[data-card]');if(card){const id=card.dataset.card,idx=state.showcase.indexOf(id);if(idx>=0)state.showcase.splice(idx,1);else if(state.showcase.length<6)state.showcase.push(id);else{note('Your Showcase is full');return}persist();draw();return}const perk=e.target.closest('[data-perk]');if(perk){const type=perk.dataset.perk,cost=type==='hint'?40:60;if(Number(window.nexusPoints)<cost){note('Earn more points first');return}window.nexusPoints=Number(window.nexusPoints)-cost;state.perks[type]=(state.perks[type]||0)+1;persist();window.save();window.render();draw();return}const action=e.target.closest('[data-action]');if(action?.dataset.action==='anomaly')startAnomaly();if(action?.dataset.action==='bonus'){const w=weekKey(),s=state.weekStats[w];if(!s||s.bonus||(s.games?.length||0)<3)return;s.bonus=true;window.nexusPoints=Number(window.nexusPoints)+40;state.totalEarned+=40;persist();window.save();window.render();draw();award('scroll')}};
  const anomalyRounds=[
    {clue:'The signal alternates two symbols. Which one follows?',pattern:'✦ ◆ ✦ ◆ ✦ ?',choices:['✦ STAR','◆ DIAMOND','● CIRCLE'],correct:1,tip:'Look for the symbol that always follows a star.'},
    {clue:'The Sensei sent a number signal. What comes next?',pattern:'2 · 4 · 6 · 8 · ?',choices:['9','10','12'],correct:1,tip:'Count forward by two.'},
    {clue:'The colors repeat in groups of three. What comes next?',pattern:'VIOLET · GOLD · BLUE · VIOLET · GOLD · ?',choices:['BLUE','GOLD','VIOLET'],correct:0,tip:'Start the group again after blue.'},
    {clue:'Each pulse adds one more star. How many are next?',pattern:'✦ · ✦✦ · ✦✦✦ · ?',choices:['2','4','5'],correct:1,tip:'Count the stars in each group.'},
    {clue:'The final gate follows this code. Which number unlocks it?',pattern:'1 · 3 · 5 · 7 · ?',choices:['8','9','10'],correct:1,tip:'The numbers are odd and rise by two.'}
  ];
  const anomaly=document.createElement('dialog');anomaly.id='nxAnomaly';anomaly.innerHTML='<div class="modal"><small>WEEKLY ANOMALY · FIVE SIGNALS</small><h2>THE SHIFTING SIGNAL</h2><p id="nxAnomalyProgress"></p><p id="nxAnomalyClue"></p><p id="nxAnomalyPattern" style="font-size:28px;text-align:center;line-height:1.5"></p><div class="choices" id="nxAnomalyChoices"></div><p id="nxFeedback" aria-live="polite"></p><button class="close" type="button">Back</button></div>';document.body.append(anomaly);anomaly.querySelector('.close').onclick=()=>anomaly.close();
  let anomalyRound=0;
  function drawAnomaly(){const r=anomalyRounds[anomalyRound];anomaly.querySelector('#nxAnomalyProgress').textContent='SIGNAL '+(anomalyRound+1)+' OF '+anomalyRounds.length;anomaly.querySelector('#nxAnomalyClue').textContent=r.clue;anomaly.querySelector('#nxAnomalyPattern').textContent=r.pattern;anomaly.querySelector('#nxAnomalyChoices').replaceChildren(...r.choices.map((choice,i)=>{const b=document.createElement('button');b.className='choice';b.type='button';b.dataset.answer=String(i);b.textContent=choice;return b}));anomaly.querySelector('#nxFeedback').textContent=''}
  function startAnomaly(){const stats=state.weekStats[weekKey()];if(stats?.anomaly)return;dlg.close();anomalyRound=0;drawAnomaly();anomaly.showModal()}
  anomaly.onclick=e=>{const b=e.target.closest('[data-answer]');if(!b)return;const r=anomalyRounds[anomalyRound];if(Number(b.dataset.answer)!==r.correct){const hint=state.perks.hint||0;if(hint){state.perks.hint--;persist()}anomaly.querySelector('#nxFeedback').textContent=hint?'Hint used: '+r.tip:'Try again. Watch the sequence carefully.';return}anomalyRound++;if(anomalyRound<anomalyRounds.length){drawAnomaly();return}const w=weekKey(),stats=state.weekStats[w]||{};if(stats.anomaly){anomaly.close();return}stats.anomaly=true;state.weekStats[w]=stats;state.totalEarned+=50;window.nexusPoints=Number(window.nexusPoints)+50;persist();window.save();window.render();anomaly.close();award('portal');setTimeout(()=>keeper('You followed every signal. The gate has noticed you.'),600)};
  window.addEventListener('nexus:played',e=>{const id=e.detail?.id;if(!id)return;const w=weekKey(),s=state.weekStats[w]||{games:[]};s.games||=[];if(!s.games.includes(id)){s.games.push(id);state.weekStats[w]=s;persist();if(dlg.open&&active==='This week')draw()}});
  const awards=['lantern','compass','scroll','key','portal'];window.addEventListener('nexus:clear',e=>{const id=e.detail?.id||'';if(!id||state.wins.includes(id))return;const count=state.wins.length;state.wins.push(id);state.totalEarned+=10;persist();award(awards[Math.min(count,awards.length-1)]);if(state.wins.length===7)award('wolf');if(state.wins.length===12)award('star')});
  window.addEventListener('nexus:signup',()=>{localStorage.setItem('nexusFirstFragmentPending','1');setTimeout(()=>keeper('Welcome to the Nexus. Your choices will shape what happens here.',true),300)});
  window.nexusUseRetry=()=>{if(!(state.perks.retry>0))return false;state.perks.retry--;persist();return true};
  window.addEventListener('nexus:points',()=>{if(dlg.open&&active==='Hero')draw()});
  if(localStorage.getItem('hahnProfile'))visit();
  window.addEventListener('nexus:signup',visit);
})();
