(() => {
  const cases = [
    {kind:'key', title:'THE MISSING NEXUS KEY', intro:'The Sensei’s key vanished before the portal opened. Follow the clues.', lead:'Where should we look first?', clues:[['Read the library log','The library log says the key was checked out for a map lesson.'],['Inspect the blue feather','A blue feather points toward the art room, where the map was being painted.'],['Ask the librarian','She saw a student return a rolled-up map, but no key.']], answer:'Inside the rolled-up map', choices:['Inside the rolled-up map','Under the lunch table','At the gym doors'], reveal:'The key slipped into the map when it was rolled up. Mystery solved!'},
    {kind:'key', title:'THE VANISHING COMPASS', intro:'The Nexus compass disappeared during a windy afternoon.',lead:'Find where it went.',clues:[['Check the windowsill','The window was open, and a ribbon is caught on the latch.'],['Ask Ana','Ana heard a metallic clink near the courtyard planters.'],['Inspect the planters','A compass-shaped mark rests in the soil behind the tallest planter.']],answer:'Behind the courtyard planter',choices:['In a classroom drawer','Behind the courtyard planter','Inside a backpack'],reveal:'The wind pushed it out the window, and it landed safely behind the planter.'},
    {kind:'key', title:'THE SECRET NOTE', intro:'A message meant for the Sensei is gone from the mission desk.',lead:'Trace the note.',clues:[['Look at the desk','A tiny purple paper corner is caught beneath a book.'],['Ask Kacee','Kacee saw loose pages fly toward the reading nook.'],['Search the reading nook','The book return slot hums with faint purple light.']],answer:'In the book return slot',choices:['In the book return slot','Under a cafeteria tray','In the lost-and-found'],reveal:'A gust slid the note into the book return. The message is safe.'},
    {kind:'impostor',title:'THE SHAPESHIFTER',intro:'One of three friends is a shapeshifter. The real friends know what happened at the portal.',lead:'Question them and spot the contradiction.',clues:[],answer:'',choices:[],reveal:''}
  ];
  const names=['Ana','Kacee','Mika'];
  let mission, seen=new Set(), round=0, suspect=0, rotating=0;
  const saved=JSON.parse(localStorage.getItem('hahnNexusCases')||'{}');
  const root=document.createElement('dialog'); root.id='nexusCasesDialog';
  root.innerHTML='<div class="nexus-cases"><header><span>✦ NEXUS CASES</span><button class="case-exit" type="button" aria-label="Close Nexus Cases">×</button></header><div class="case-art" role="img" aria-label="Illustrated mysterious library and portal"></div><div class="case-content"><div class="case-meta" id="caseMeta"></div><h2 id="caseTitle"></h2><p id="caseText"></p><div class="case-clues" id="caseClues"></div><div class="case-actions" id="caseActions"></div></div></div>';
  document.body.append(root);
  const $=id=>root.querySelector('#'+id), actions=$('caseActions'), clues=$('caseClues');
  root.querySelector('.case-exit').onclick=()=>root.close();
  root.addEventListener('click',e=>{if(e.target===root)root.close()});
  function button(label,fn,disabled=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=disabled;b.onclick=fn;actions.append(b)}
  function layout(title,body,meta){$('caseTitle').textContent=title;$('caseText').textContent=body;$('caseMeta').textContent=meta;actions.replaceChildren();clues.replaceChildren()}
  function home(){layout('CHOOSE YOUR NEXT CASE','Each mission is a quick solo mystery. Investigate, then make your call.','ROTATING MISSIONS · SOLO');button('▶ SURPRISE ME',()=>start());button('🔑 MISSING OBJECT',()=>start('key'));button('🎭 FIND THE IMPOSTOR',()=>start('impostor'));const n=Object.keys(saved).length;if(n){const p=document.createElement('p');p.textContent=n+' case'+(n===1?'':'s')+' solved · first-clear rewards saved';clues.append(p)}}
  function start(kind){let pool=cases.filter(c=>!kind||c.kind===kind);if(!kind&&round++%2)pool=cases.filter(c=>c.kind==='impostor');const c=pool[rotating++%pool.length];mission={...c,id:c.kind==='impostor'?'impostor-'+(Math.floor(Math.random()*3)):c.title,clues:c.clues.map(a=>a.slice())};seen=new Set();if(c.kind==='impostor')setupImpostor();draw()}
  function setupImpostor(){suspect=Math.floor(Math.random()*3);const fact=['The portal glowed violet','The key was on the desk','The bell rang twice'][Math.floor(Math.random()*3)];mission.intro='Three friends say they saw the portal open. One is a shapeshifter. Find the story that does not fit.';mission.clues=names.map((n,i)=>['Question '+n,i===suspect?n+' insists the portal glowed green. The mission log says: '+fact+'.':n+' remembers: '+fact+'.']);mission.answer=names[suspect];mission.choices=[...names];mission.reveal=names[suspect]+' gave the story that contradicted the mission log. You found the shapeshifter!';mission.fact=fact}
  function draw(){layout(mission.title,mission.intro+' '+mission.lead,seen.size+' / 3 CLUES FOUND');mission.clues.forEach(([label,detail],i)=>button((seen.has(i)?'✓ ':'🔎 ')+label,()=>{seen.add(i);const row=document.createElement('p');row.textContent=detail;clues.append(row);drawClues();},seen.has(i)));button(seen.size>=2?'MAKE YOUR CALL →':'FIND 2 CLUES TO CONTINUE',accuse,seen.size<2);button('↩ CASE SELECT',home);drawClues()}
  function drawClues(){clues.replaceChildren();[...seen].forEach(i=>{const p=document.createElement('p');p.textContent=mission.clues[i][1];clues.append(p)});$('caseMeta').textContent=seen.size+' / 3 CLUES FOUND';const call=actions.querySelectorAll('button')[3];call.disabled=seen.size<2;call.textContent=seen.size>=2?'MAKE YOUR CALL →':'FIND 2 CLUES TO CONTINUE'}
  function accuse(){layout('THE FINAL CALL',mission.kind==='impostor'?'Who is the shapeshifter?':'Where is the missing item?','EVIDENCE READY');mission.choices.forEach(choice=>button(choice,()=>finish(choice)));button('← REVIEW CLUES',draw)}
  function finish(choice){const correct=choice===mission.answer;layout(correct?'CASE SOLVED!':'KEEP INVESTIGATING',correct?mission.reveal:'That guess does not fit the clues. Read them again and try another answer.',correct?'✦ MISSION COMPLETE':'THE CASE IS STILL OPEN');if(correct){if(!saved[mission.id]){saved[mission.id]=true;localStorage.setItem('hahnNexusCases',JSON.stringify(saved));if(typeof points!=='undefined'&&typeof save==='function'){points=Number(points)+20;save();render()}const p=document.createElement('p');p.textContent='First solve: +20 hero points';clues.append(p);window.dispatchEvent(new CustomEvent('nexus:clear',{detail:{id:'nexus-case-'+mission.id}}))}else{const p=document.createElement('p');p.textContent='Solved before · no repeat points';clues.append(p)}button('NEXT MISSION →',()=>start());button('CASE SELECT',home)}else{button('REVIEW CLUES',draw);button('TRY ANOTHER ANSWER',accuse)}}
  document.getElementById('openNexusCases').onclick=()=>{document.getElementById('gamesDialog').close();root.showModal();home()};
})();
