(()=>{'use strict';
const URL='https://reccddfusealreknvjfj.supabase.co/functions/v1/nexus';
const KEY='REPLACE_WITH_YOUR_API_KEY';
const titles={odin:'ODIN',tapple:'Nexus Word Rush (Tapple)',shadow:'Shadow Signal',memory:'Memory Flip',trivia:'Trivia Clash',pattern:'Pattern Pulse',scramble:'Word Scramble',spot:'Spot the Difference'};
const names={lantern:'Lantern Fragment',compass:'Wandering Compass',scroll:'Mission Scroll',key:'Hidden Gate Key',portal:'Portal Echo',wolf:'First Keeper’s Sigil',star:'Nexus Star'};
const rarities={lantern:'Common',compass:'Common',scroll:'Uncommon',key:'Rare',portal:'Epic',wolf:'Legendary',star:'Mythic'};
const arts={lantern:'notebook',compass:'compass',scroll:'mission-scroll',key:'nexus-key',portal:'portal',wolf:'wolf',star:'card-back'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const d=document.createElement('dialog');d.id='onlineDialog';d.innerHTML='<div class="on-shell"><header><div><small>SQUAD HQ · ONLINE</small><h2 id="onTitle">PLAY WITH YOUR SQUAD</h2></div><button id="onClose" aria-label="Back to HQ">×</button></header><p id="onStatus" role="status" aria-live="polite"></p><div id="onBody"></div></div>';document.body.append(d);
const body=d.querySelector('#onBody'),status=d.querySelector('#onStatus');
let secret=localStorage.getItem('nexusOnlineSecret'),player=null,room=null,trade=null,mode='home',timer=null,busy=false,signature='',dirty=false;
const last=JSON.parse(localStorage.getItem('nexusOnlineRoom')||'null');
async function api(op,data={}){const r=await fetch(URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({op,secret,...data})});const v=await r.json();if(!r.ok||v.error)throw Error(v.error||'Connection interrupted. Try again.');return v}
async function connected(){if(!secret){const r=await api('register');secret=r.secret;player=r.player;localStorage.setItem('nexusOnlineSecret',secret)}else if(!player){const r=await api('inventory');player=r.player}return player}
function message(s){status.textContent=s}
async function run(fn){if(busy)return;busy=true;message('Connecting…');try{await connected();await fn();message('Connected as '+player.nickname)}catch(e){message(e.message)}finally{busy=false}}
function heading(s){d.querySelector('#onTitle').textContent=s}
function home(){mode='home';signature='';heading('PLAY WITH YOUR SQUAD');body.innerHTML=`<p>Create a private room. Share its code with friends so they can join from their own devices.</p><div class="on-games">${Object.entries(titles).map(([id,t])=>`<button data-create="${id}">${esc(t)}</button>`).join('')}</div><form id="onJoin"><label for="onCode">Room code</label><div class="on-row"><input id="onCode" name="code" maxlength="8" autocomplete="off" autocapitalize="characters" required placeholder="8-letter code"><button>JOIN ROOM</button></div></form>${last?`<button data-rejoin>REJOIN ${esc(last.game?titles[last.game]:'ROOM')} · ${esc(last.code)}</button>`:''}<button data-trade-home>TRADE CARDS WITH A FRIEND</button><p class="on-muted">Room codes expire after 24 hours. Your online hero stays connected on this device. Online cards are earned here and kept by the server; your existing device collection stays available in the Vault.</p>`}
function score(r){return `<div class="on-players">${r.players.map((p,i)=>`<span class="${r.phase==='playing'&&i===r.turn?'on-current':''}">${esc(p.nickname)}${p.id===player.id?' (you)':''} · ${p.score}${r.handCounts?' · '+r.handCounts[p.id]+' cards':''}</span>`).join('')}</div>`}
function drawRoom(r,force=false){room=r;mode='room';localStorage.setItem('nexusOnlineRoom',JSON.stringify({code:r.code,game:r.game}));const sig=r.code+':'+r.revision;if(sig===signature&&!force)return;signature=sig;heading(titles[r.game]);
let html=`<div class="on-room-code">ROOM <strong>${esc(r.code)}</strong><button data-copy="${esc(r.code)}">COPY CODE</button></div>${score(r)}`;
if(r.phase==='lobby'){html+=`<p>${r.players.length} of 8 heroes connected. ${r.game==='shadow'?'Invite at least 3 heroes.':'At least 2 heroes needed.'}</p><p>${r.game==='odin'?'Match the color or number. Skip, Reverse and +2 change turns; Wild lets you choose a color. First to empty their hand wins.':r.game==='tapple'?'Name an animal or food beginning with an unused letter before the timer runs out.':r.game==='shadow'?'One hero gets a hidden Shadow role. Ask each other clues aloud, then vote. Keep your screen secret.':'Everyone sees the same challenge. The server keeps the scores.'}</p>${r.host===player.id?'<button data-start>START GAME</button>':'<p>Waiting for the room creator to start…</p>'}<button data-leave>LEAVE ROOM</button>`}
else if(r.phase==='finished'){html+=`<h3>ROUND COMPLETE!</h3><p>${r.winners.map(id=>esc(r.players.find(p=>p.id===id)?.nickname)).join(' & ')} ${r.winners.length===1?'wins':'tie'}!</p>${r.spy?`<p>The Shadow was ${esc(r.players.find(p=>p.id===r.spy)?.nickname)}. Location: ${esc(r.word)}</p>`:''}<p>An online fragment has been added to each hero’s collection. Milestones unlock rarer cards.</p><button data-home>PLAY ANOTHER GAME</button><button data-trade-home>OPEN ONLINE CARDS</button>`}
else{
const turn=r.players[r.turn]?.id===player.id;html+=`<div class="on-round"><strong>${['odin','tapple','memory'].includes(r.game)?turn?'YOUR TURN':esc(r.players[r.turn]?.nickname)+"’s turn":r.game==='shadow'?'KEEP YOUR ROLE SECRET':'ROUND '+(r.round+1)+' / 10'}</strong><span id="onTimer"></span></div>`;
if(r.game==='odin'){html+=`<p>Match color or number. Action cards: Skip, Reverse, +2, Wild.</p><label for="onWild">Wild color</label><select id="onWild"><option value="violet">Violet</option><option value="blue">Blue</option><option value="green">Green</option><option value="gold">Gold</option></select><div class="on-top" style="--card:${r.top.color}">${r.top.value}</div><div class="on-hand" style="--count:${r.hand.length}">${r.hand.map((c,i)=>`<button class="on-card ${c.color}" data-play="${i}" ${!turn?'disabled':''} aria-label="${c.color} ${c.value}"><span>${c.value}</span><small>${c.color}</small></button>`).join('')}</div><div class="on-row"><button data-draw ${!turn||r.drawn?'disabled':''}>DRAW</button><button data-pass ${!turn?'disabled':''}>PASS</button></div>`}
if(r.game==='memory'){const icons=['⚡','🌙','⭐','🔥','🌊','🍀','🦊','🐺'];html+=`<div class="on-memory">${r.board.map((c,i)=>`<button data-flip="${i}" ${!turn||c!==null||r.hideAt?'disabled':''} aria-label="${c===null?'Hidden card '+(i+1):'Revealed '+icons[c]}">${c===null?'✦':icons[c]}</button>`).join('')}</div>`}
if(r.game==='tapple'){html+=`<h3>${esc(r.category).toUpperCase()}</h3><div class="on-letters">${'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(l=>`<span class="${r.used.includes(l.toLowerCase())?'used':''}">${l}</span>`).join('')}</div><form id="onWord"><label for="onAnswer">${turn?'Name a '+(r.category==='Animals'?'real animal':'food'):'Waiting for your turn'}</label><div class="on-row"><input id="onAnswer" name="answer" maxlength="24" required ${!turn?'disabled':''} autocomplete="off"><button ${!turn?'disabled':''}>SEND WORD</button></div></form><p class="on-muted">One word per letter. Familiar words work best; “icecream” counts as I. Eliminated heroes: ${r.eliminated.map(id=>esc(r.players.find(p=>p.id===id)?.nickname)).join(', ')||'none'}</p>`}
if(r.game==='shadow'){const voted=r.votes.includes(player.id);html+=`<div class="on-secret"><strong>YOU ARE THE ${esc(r.role).toUpperCase()}</strong><p>${esc(r.secret)}</p></div><p>Take turns giving a clue aloud. Which hero is the Shadow? You get one vote.</p><div class="on-games">${r.players.filter(p=>p.id!==player.id).map(p=>`<button data-vote="${p.id}" ${voted?'disabled':''}>${esc(p.nickname)}</button>`).join('')}</div><p>${r.votes.length} of ${r.players.length} votes received.</p>`}
if(['trivia','pattern','scramble'].includes(r.game)){const answered=r.answered.includes(player.id);html+=`<h3>${esc(r.game==='trivia'?r.question[0]:r.prompt)}</h3>`;if(r.game==='scramble')html+=`<form id="onWord"><label for="onAnswer">Unscramble the word</label><div class="on-row"><input id="onAnswer" name="answer" maxlength="24" required ${answered?'disabled':''} autocomplete="off"><button ${answered?'disabled':''}>ANSWER</button></div></form>`;else html+=`<div class="on-games">${(r.game==='trivia'?r.question[1]:r.options).map((a,i)=>`<button data-answer="${r.game==='trivia'?i:a}" ${answered?'disabled':''}>${esc(a)}</button>`).join('')}</div>`;html+=`<p>${answered?'Answer saved. Waiting for the squad…':'Everyone answers once per round.'}</p>`}
if(r.game==='spot'){html+=`<p>Tap either picture to find the five differences. ${r.found.length} / 5 found.</p><div class="on-spot"><img id="onSpot" src="spot-difference/set-${r.set+1}.jpg" alt="Two pictures to compare. Tap a difference."></div>`}
html+='<button data-home>BACK TO SQUAD HQ</button>';}
body.innerHTML=html;updateTimer();}
function updateTimer(){const el=d.querySelector('#onTimer');if(el&&room?.deadline)el.textContent=Math.max(0,Math.ceil((room.deadline-Date.now())/1000))+'s'}
async function tradeHome(){mode='trade-home';signature='';heading('ONLINE CARD TRADING');const inv=await api('inventory');body.innerHTML=`<p>Both heroes review the exact exchange. Changing cards resets both confirmations. Uneven trades show a warning; extremely uneven trades are blocked.</p><button data-new-trade>CREATE A TRADE</button><form id="onTradeJoin"><label for="onTradeCode">Friend’s trade code</label><div class="on-row"><input id="onTradeCode" name="code" maxlength="8" required placeholder="8-letter code" autocomplete="off" autocapitalize="characters"><button>JOIN TRADE</button></div></form><h3>YOUR SERVER-VERIFIED CARDS · ${inv.cards.length}</h3><div class="on-inventory">${inv.cards.map(c=>`<div class="on-fragment"><img src="memory-art/${arts[c.card]}.jpg" alt=""><strong>${esc(names[c.card])}</strong><small>${rarities[c.card]}</small></div>`).join('')}</div><p class="on-muted">Finish squad rounds to earn fragments. Complete 7, 12, 20 and 30 rounds to discover Rare, Epic, Legendary and Mythic cards.</p><button data-home>BACK TO SQUAD HQ</button>`}
function offerHTML(ids,t){return ids.map(id=>{const c=t.cards.find(c=>c.id===id);return `<li>${esc(names[c?.card]||'Card transferred')} <small>${rarities[c?.card]||''}</small></li>`}).join('')||'<li>No cards offered</li>'}
function drawTrade(t,force=false){trade=t;mode='trade';const sig=t.code+':'+t.revision+':'+t.confirmed_a+':'+t.confirmed_b+':'+t.status+':'+!!t.b;if(sig===signature&&!force)return;signature=sig;dirty=false;heading('TRADE WITH A FRIEND');
const mine=t.side==='a'?t.offer_a:t.offer_b;const myConfirm=t.side==='a'?t.confirmed_a:t.confirmed_b;const otherConfirm=t.side==='a'?t.confirmed_b:t.confirmed_a;
body.innerHTML=`<div class="on-room-code">TRADE <strong>${esc(t.code)}</strong><button data-copy="${esc(t.code)}">COPY CODE</button></div><p>${t.status==='open'?t.b?'Your friend is connected. Review both sides.':'Share this code with your friend.':t.status==='completed'?'Trade complete! Both collections have been updated.':'Trade cancelled.'}</p><div class="on-exchange"><section><h3>YOU GIVE · ${t.values?.[t.side]||0}</h3><ul>${offerHTML(mine,t)}</ul></section><section><h3>YOU RECEIVE · ${t.values?.[t.side==='a'?'b':'a']||0}</h3><ul>${offerHTML(t.side==='a'?t.offer_b:t.offer_a,t)}</ul></section></div>${t.status==='open'?`<div class="on-fairness ${t.fairness}">${t.fairness==='blocked'?'This trade is too lopsided. Balance the cards first.':t.fairness==='uneven'?`Hold up! This trade looks uneven. ${t.givingMore===t.side?'You are':'Your friend is'} giving away more. Are you sure?`:t.fairness==='balanced'?'This trade looks balanced.':'Both heroes must offer cards.'}</div><form id="onOffer"><fieldset><legend>Choose the card copies you want to give</legend><div class="on-offer">${t.cards.filter(c=>c.owner===player.id).map(c=>`<label><input type="checkbox" name="card" value="${c.id}" ${mine.includes(c.id)?'checked':''}>${esc(names[c.card])} <small>${rarities[c.card]}</small></label>`).join('')}</div></fieldset><button>SAVE MY OFFER</button></form><p id="onDirty" class="on-muted">Any offer change resets both confirmations.</p>${t.fairness==='uneven'?'<label class="on-ack"><input id="onAck" type="checkbox">I reviewed the uneven trade and still want to continue.</label>':''}<button data-confirm ${!t.b||['incomplete','blocked'].includes(t.fairness)||myConfirm===t.revision?'disabled':''}>${myConfirm===t.revision?'YOU CONFIRMED':'CONFIRM THIS EXACT TRADE'}</button><p>${otherConfirm===t.revision?'Your friend confirmed.':'Waiting for your friend’s confirmation.'}</p><button data-cancel-trade>CANCEL TRADE</button>`:''}<button data-trade-home>BACK TO ONLINE CARDS</button>`;}
async function refresh(){if(busy||!d.open)return;try{if(mode==='room'&&room)drawRoom(await api('room-state',{code:room.code}));if(mode==='trade'&&trade){const t=await api('trade-state',{code:trade.code});drawTrade(t)}updateTimer()}catch(e){message(e.message+' · reconnecting…')}}
function open(){document.querySelector('#squadDialog')?.close();if(!d.open)d.showModal();home();run(async()=>{});clearInterval(timer);timer=setInterval(refresh,1500)}
window.nexusOpenOnline=open;
const rush=document.querySelector('#openWordRush');if(rush){const replacement=rush.cloneNode(true);replacement.textContent='⚡ NEXUS WORD RUSH · ONLINE';rush.replaceWith(replacement);replacement.onclick=()=>{document.querySelector('#gamesDialog').close();open()};}
d.querySelector('#onClose').onclick=()=>d.close();d.addEventListener('close',()=>clearInterval(timer));
document.querySelector('#squadDialog').innerHTML='<div class="modal"><small>SQUAD HQ</small><h2>PLAY TOGETHER</h2><p>Create a private room, play from separate devices, or trade online cards.</p><button class="choice" id="onSquadLaunch">OPEN ONLINE SQUAD HQ</button><button class="close">Back to HQ</button></div>';
document.querySelector('#onSquadLaunch').onclick=open;document.querySelector('#squadDialog .close').onclick=()=>document.querySelector('#squadDialog').close();
const gameButton=document.createElement('button');gameButton.className='choice';gameButton.textContent='👥 ONLINE SQUAD GAMES';gameButton.onclick=()=>{document.querySelector('#gamesDialog').close();open()};document.querySelector('#gamesDialog .choices').prepend(gameButton);
body.addEventListener('change',e=>{if(e.target.matches('#onOffer input')){dirty=true;body.querySelector('[data-confirm]').disabled=true;body.querySelector('#onDirty').textContent='Save your changed offer before confirming.'}});
body.addEventListener('submit',e=>{e.preventDefault();const f=e.target;if(f.id==='onJoin')run(async()=>drawRoom(await api('room-join',{code:new FormData(f).get('code')}),true));if(f.id==='onTradeJoin')run(async()=>drawTrade(await api('trade-join',{code:new FormData(f).get('code')}),true));if(f.id==='onWord'){const answer=new FormData(f).get('answer');run(async()=>drawRoom(await api('room-move',{code:room.code,revision:room.revision,move:room.game==='tapple'?{word:answer}:{round:room.round,answer}}),true))}if(f.id==='onOffer'){const cards=new FormData(f).getAll('card');run(async()=>drawTrade(await api('trade-offer',{code:trade.code,revision:trade.revision,cards}),true))}});
body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const a=b.dataset;
if('home'in a){home();return}if('tradeHome'in a){run(tradeHome);return}if('copy'in a){navigator.clipboard?.writeText(a.copy).then(()=>message('Code copied')).catch(()=>message('Share this code: '+a.copy));return}
if('create'in a)run(async()=>drawRoom(await api('room-create',{game:a.create}),true));if('rejoin'in a)run(async()=>drawRoom(await api('room-join',{code:last.code}),true));if('start'in a)run(async()=>drawRoom(await api('room-start',{code:room.code}),true));if('leave'in a)run(async()=>{await api('room-leave',{code:room.code});localStorage.removeItem('nexusOnlineRoom');room=null;home()});
let m;if('play'in a)m={index:Number(a.play),type:'play',color:d.querySelector('#onWild')?.value};if('draw'in a)m={type:'draw'};if('pass'in a)m={type:'pass'};if('flip'in a)m={index:Number(a.flip)};if('vote'in a)m={vote:a.vote};if('answer'in a)m={answer:a.answer,round:room.round};if(m)run(async()=>drawRoom(await api('room-move',{code:room.code,revision:room.revision,move:m}),true));
if('newTrade'in a)run(async()=>{const t=await api('trade-create');drawTrade(await api('trade-state',{code:t.code}),true)});
if('confirm'in a){if(dirty)return;if(trade.fairness==='uneven'&&!d.querySelector('#onAck')?.checked){message('Check the uneven-trade warning before confirming.');return}run(async()=>drawTrade(await api('trade-confirm',{code:trade.code,revision:trade.revision,ack:!!d.querySelector('#onAck')?.checked}),true))}
if('cancelTrade'in a)run(async()=>drawTrade(await api('trade-cancel',{code:trade.code,revision:trade.revision}),true));});
body.addEventListener('click',e=>{if(e.target.id!=='onSpot'||busy)return;const image=e.target,box=image.getBoundingClientRect(),x=(e.clientX-box.left)/box.width,y=(e.clientY-box.top)/box.height;run(async()=>drawRoom(await api('room-move',{code:room.code,revision:room.revision,move:{x,y}}),true))});
})();
