(()=>{
const page=document.querySelector('#portalPreview');if(!page)return;
const $=s=>page.querySelector(s);
const esc=s=>{const d=document.createElement('div');d.textContent=String(s);return d.innerHTML};
let role='parent';
const labels={parent:['Overview','Add Chore','Approvals','Learning'],teacher:['Overview','Assignment','Review','Learning']};
const panels={
 parent:[
 `<h3>Family dashboard</h3><div class="portal-card"><strong>Connect a child</strong><small>When accounts launch, your child can enter your email and you will receive a private invitation link.</small></div><div class="portal-card"><strong>Chores and points</strong><small>See submitted chores, approve them, and track points here after connection.</small></div>`,
 `<h3>Add a chore</h3><p class="portal-muted">Try the form. Previewing does not send a chore or award points.</p><label>Chore name<input id="previewChore" maxlength="80" placeholder="For example: Make your bed"></label><label>Repeat<select id="previewFrequency"><option>One time</option><option>Daily</option><option>Weekly</option><option>Anytime</option></select></label><label>Points<input id="previewPoints" type="number" min="0" max="100" value="10"></label><button class="portal-action" type="button" id="previewChoreButton">Preview chore</button><div id="previewChoreResult" aria-live="polite"></div>`,
 `<h3>Approve completed chores</h3><div class="portal-card">No child is connected yet. Submitted chores will appear here, and points will post only after your approval.</div>`,
 `<h3>Learning progress</h3><p class="portal-muted">After your account is connected, you will see each child’s strengths, practice areas, and recent results. The sample below uses answers saved on this device only.</p><div class="portal-learning"></div>`
 ],teacher:[
 `<h3>Class dashboard</h3><div class="portal-card"><strong>Connect students</strong><small>Students will enter your teacher code in Settings. Your linked students and their work will appear here.</small></div><div class="portal-card"><strong>Assignment review</strong><small>See completion, correct and missed answers, topic progress, and an Approve button at 100% completion.</small></div>`,
 `<h3>Make an assignment</h3><p class="portal-muted">Paste questions or work into one box. Previewing only splits paragraphs; questions and answers must be checked before a real assignment can be published.</p><label>Assignment title<input id="previewAssignmentTitle" maxlength="80" placeholder="For example: Fraction practice"></label><label>Paste work<textarea id="previewAssignmentText" placeholder="Paste your work here"></textarea></label><button class="portal-action" type="button" id="previewAssignmentButton">Preview text</button><div id="previewAssignmentResult" aria-live="polite"></div>`,
 `<h3>Review student work</h3><div class="portal-card">No students are linked yet. Completion percentage, question counts, right and wrong answers, and approval will appear here.</div>`,
 `<h3>Learning results</h3><p class="portal-muted">When connected, teachers will see each student’s topic results and missed questions. This device’s local answers are shown below only as a layout preview.</p><div class="portal-learning"></div>`
 ]};
function learning(){let entries=[];try{entries=JSON.parse(localStorage.getItem('hahnLearningProgress')||'[]')}catch{}const groups={};for(const e of entries)(groups[e.topic]??=[]).push(e);const html=Object.entries(groups).map(([topic,list])=>{const recent=list.slice(-7),right=recent.filter(x=>x.correct).length,label=recent.length<5?'Early results':right/recent.length>=.8?'Strong':right/recent.length>=.55?'Developing':'Needs practice';return `<div class="portal-card"><strong>${esc(topic)} · ${label}</strong><small>${right} of ${recent.length} recent answers correct on this device</small></div>`}).join('');page.querySelectorAll('.portal-learning').forEach(el=>el.innerHTML=html||'<div class="portal-card">No learning answers saved on this device yet.</div>')}
function showTab(n){$('.portal-tabs').innerHTML=labels[role].map((s,i)=>`<button type="button" data-tab="${i}" aria-selected="${i===n}">${s}</button>`).join('');$('.portal-panel').innerHTML=panels[role][n];learning()}
function open(next){role=next;$('#portalTitle').textContent=role==='parent'?'Parent Portal':'Teacher Portal';$('#portalKind').textContent=role==='parent'?'FAMILY HQ':'CLASS HQ';showTab(0);document.querySelector('#settingsDialog')?.close();page.showModal()}
document.querySelectorAll('[data-portal]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.portal)));
page.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){showTab(Number(tab.dataset.tab));return}if(e.target.closest('#portalExit')){page.close();return}if(e.target.closest('#previewChoreButton')){const title=$('#previewChore').value.trim(),points=Number($('#previewPoints').value);$('#previewChoreResult').innerHTML=title&&Number.isInteger(points)&&points>=0&&points<=100?`<div class="portal-card"><strong>${esc(title)}</strong><small>${esc($('#previewFrequency').value)} · ${points} points · preview only</small></div>`:'<p>Enter a chore name and 0–100 points.</p>'}if(e.target.closest('#previewAssignmentButton')){const blocks=$('#previewAssignmentText').value.trim().split(/\n\s*\n|\n(?=\d+[.)]\s)/).map(x=>x.trim()).filter(Boolean);$('#previewAssignmentResult').innerHTML=blocks.length?`<div class="portal-card"><strong>${blocks.length} draft block${blocks.length===1?'':'s'}</strong><small>Review question breaks and answer keys before publishing.</small></div>`:'<p>Paste some work to preview it.</p>'}});
})();
